# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
resources:
  repositories:
    - repository: ADF # Required as first property. Alias for the repository.
    # ID of the service endpoint connecting to this repository.
      # CI trigger for this repository, no CI trigger if skipped (only works for Azure Repos).
      name: ADF # repository name (format depends on 'type'; does not accept variables).
      ref: dev # ref name to checkout; defaults to 'refs/heads/main'. The branch checked out by default whenever the resource trigger fires.
      type: git # Type of repository: git, github, githubenterprise, and bitbucket.

pool:
  vmImage: windows-latest
variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm  



steps:
- checkout: self
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    restoreKeys: |
       npm | "$(Agent.OS)"
    path: $(npm_config_cache)
  displayName: Cache npm


- script: |
    npm install -g @angular/cli
    npm install --verbose
    ng build --prod
  displayName: 'npm install and build'
- script: ls -a
