name: angular
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4.0.2
      with:
         node-version: 20
    
    - uses: actions/checkout@v4.1.4
   
    - run: |
        npm install -g @angular/cli
        npm install --verbose
        ng build --prod
    - uses: actions/upload-artifact@v4.3.3
      with:
        name: drop
        path: dist/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: echo "test"
        
    
