name: angular
permissions:
  id-token: write
  contents: read

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4.0.2
      with:
         node-version: 16.14.x
    
    - uses: actions/checkout@v4.1.4
   
    - run: |
        npm install -g @angular/cli@16.1.x
        yarn install --verbose
        ng build --prod
    - uses: actions/upload-artifact@v4.3.3
      with:
        name: drop
        path: dist/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4.1.7
      with:
        name: drop
    - run: ls
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: Azure/webapps-deploy@v3.0.1
      with:
        app-name: angularcheck
        package: .
      

        
    
